apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: argocd
spec:
  project: observability
  source:
    repoURL: https://github.com/MissTipo/platform-gitops
    targetRevision: main
    path: platform/tempo
  destination:
    server: https://kubernetes.default.svc
    namespace: tracing
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

