apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admin@example.com

    privateKeySecretRef:
      name: letsencrypt-private-key

    solvers:
      - dns01:
          oci:
            config:
              tenancy: ${OCI_TENANCY_OCID}
              user: ${OCI_USER_OCID}
              fingerprint: ${OCI_FINGERPRINT}
              region: ${OCI_REGION}
              compartmentId: ${OCI_COMPARTMENT_OCID}

              privateKeySecretRef:
                name: oci-api-key
                key: private_key

